import type { Metadata } from "next"
import { Poppins, Poiret_One } from "next/font/google"

import "./globals.scss"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
})

const poiret_one_init = Poiret_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poiret_one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${poiret_one_init.variable}`}>
        <main className={`overflow-hidden bg-[#fff]`}>{children}</main>
      </body>
    </html>
  );
}
